server:
  port: 6000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 20
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 10
    disable-delta: false   # keep delta enabled for performance
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2000ms
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # AUTH SERVICE
            - id: auth-routes
              uri: lb://user-service
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: user-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: auth-user-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # USERS
            - id: user-service-routes
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: user-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: user-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # AIRLINE
            - id: airline-core-routes
              uri: lb://airline-core-service
              predicates:
                - Path=/api/v1/airlines/**,/api/v1/aircrafts/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: airline-core-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: airline-core-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # SEAT
            - id: seat-service-routes
              uri: lb://seat-service
              predicates:
                - Path=/api/v1/cabin-classes/**,/api/v1/seat-maps/**,/api/v1/seats/**,/api/v1/seat-instances/**,/api/v1/flight-instance-cabins/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: seat-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: seat-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # FLIGHT OPS
            - id: flight-ops-service-routes
              uri: lb://flight-ops-service
              predicates:
                - Path=/api/v1/flights/**,/api/v1/flight-instances/**,/api/v1/flight-schedules/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: flight-ops-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: flight-ops-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # PRICING
            - id: pricing-service-routes
              uri: lb://pricing-service
              predicates:
                - Path=/api/v1/fares/**,/api/v1/fare-rules/**,/api/v1/baggage-policies/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: pricing-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: pricing-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # ANCILLARY
            - id: ancillary-service-routes
              uri: lb://ancillary-service
              predicates:
                - Path=/api/v1/meals/**,/api/v1/ancillaries/**,/api/v1/insurance-coverages/**,/api/v1/flight-meals/**,/api/v1/flight-cabin-ancillaries/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: ancillary-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: ancillary-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # LOCATION
            - id: location-service-routes
              uri: lb://location-service
              predicates:
                - Path=/api/v1/cities/**,/api/v1/airports/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: location-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: location-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # BOOKING
            - id: location-service-routes
              uri: lb://location-service
              predicates:
                - Path=/api/v1/cities/**,/api/v1/airports/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: location-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: location-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # PAYMENT
            - id: payment-service-routes
              uri: lb://location-service
              predicates:
                - Path=/api/v1/cities/**,/api/v1/airports/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: location-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: location-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # ADMIN CITY ROUTES
            - id: admin-location-routes
              uri: lb://location-service
              predicates:
                - Path=/api/v1/cities/**,/api/v1/airports/**
                - Method=POST
              filters:
                - Role=ROLE_SYSTEM_ADMIN
                - name: CircuitBreaker
                  args:
                    name: location-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: admin-location-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

            # ADMIN AIRLINE ROUTES
            - id: admin-airline-core-routes
              uri: lb://airline-core-service
              predicates:
                - Path=/api/v1/airlines/**
                - Method=GET
              filters:
                - Role=ROLE_SYSTEM_ADMIN
                - name: CircuitBreaker
                  args:
                    name: airline-core-service-cb
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    name: admin-airline-core-service-rrl
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.eureka: DEBUG
    reactor.netty: DEBUG
    io.netty: INFO


resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
        cancel-running-future: true
    instances:
      booking-service-cb:
        timeout-duration: 8s
      payment-service-cb:
        timeout-duration: 10s
  circuitbreaker:
    configs:
      gateway-default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
    instances:
      booking-service-cb:
        base-config: gateway-default
        failure-rate-threshold: 40
        wait-duration-in-open-state: 45s
      payment-service-cb:
        base-config: gateway-default
        failure-rate-threshold: 30
        wait-duration-in-open-state: 60s
      flight-ops-service-cb:
        base-config: gateway-default
      seat-service-cb:
        base-config: gateway-default
      pricing-service-cb:
        base-config: gateway-default
      ancillary-service-cb:
        base-config: gateway-default
      location-service-cb:
        base-config: gateway-default
      airline-core-service-cb:
        base-config: gateway-default
      user-service-cb:
        base-config: gateway-default