server:
  port: 5005
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: NEVER
      platform: postgres
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: flight-ops-service-group

eureka:
  client:
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: flight-ops-service