server:
  port: 5010
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:airline-admin@gmail.com}
    password: ${MAIL_APP_PASSWORD:pnrb gkyu brhr eexo}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
  eureka:
    client:
      register-with-eureka: true
    instance:
      prefer-ip-address: false
      hostname: notification-service

notification:
  from-email: ${MAIL_FROM:airline-admin@gmail.com}
  from-name: Airline Notification
  checkin-url: "frontend url"